FROM denoland/deno:alpine AS base

FROM base AS deps
WORKDIR /app
COPY . /app/
RUN deno install
RUN deno run generate-db
RUN deno task build:rolldown
RUN deno compile --no-check \
    --allow-env --allow-read \
    --allow-sys=hostname --allow-net \
    -o /yarik ./bundle.cjs

FROM debian:trixie-slim AS runner
COPY --from=deps /yarik /yarik
COPY --from=deps /app/generated/ /app/
EXPOSE 3000
ENV PORT=3000
CMD [ "/yarik" ]