FROM denoland/deno:alpine AS base

FROM base AS deps
WORKDIR /app
COPY . /app/
RUN deno install
RUN deno run generate-db
RUN deno task build

FROM base AS runner
WORKDIR /app/
COPY --from=deps /app/bundle.cjs /app/bundle.cjs
COPY --from=deps /app/generated/ /app/
EXPOSE 3000
ENV PORT=3000
CMD [ "deno", "-A", "bundle.cjs" ]